include /opt/theos/makefiles/common.mk

TWEAK_NAME = UnAlarm
UnAlarm_FILES = Tweak.xm
UnAlarm_FRAMEWORKS = UIKit AVFoundation
SUBPROJECTS = unalarmsettings
include $(THEOS_MAKE_PATH)/tweak.mk
include $(THEOS_MAKE_PATH)/aggregate.mk